### ISSUE TITLE
再aarch64 晶晨s905x3 运行失败

### ISSUE THREAD

**Issue by rq1025330** [bauw2008/op#1]
![image](https://github.com/bauw2008/op/assets/52870887/66b3bb1c-efc5-42a4-958f-75c0a7b319ad)
 大佬能否支持下这个芯片类型

**Comment by bauw2008** [comment]
这是自备用仓库，只适用x86，其他平台没测试。

**Comment by rq1025330** [comment]
> 这是自备仓库，仅适用x86，其他平台未测试。

全网就搜索到你这个仓库  实在需要这个  大佬有空能否测试下呢？

**Comment by rq1025330** [comment]
> 这是自备仓库，仅适用x86，其他平台未测试。

全网就搜索到你有这个软件 ，确实需要这个软件，大佬能否有空的时候测试下呢？

**Comment by rq1025330** [comment]
> 这是自备用仓库，只适用x86，其他平台没测试。
![image](https://github.com/bauw2008/op/assets/52870887/93e856e2-c4b4-4bc5-9574-1248fa3395e2)
是不是这里足额个文件 ，这个文件怎么编译成的呢 ，不会软件呢。

**Comment by bauw2008** [comment]
图片是官方二进制内核文件，和平台不兼容是启动不了的。建议你刷Armbian，用cups做打印服务器更稳定。

**Comment by rq1025330** [comment]
> 图片是官方二进制内核文件，和平台不兼容是启动不了的。建议你刷Armbian，用cups做打印服务器更稳定。

![image](https://github.com/bauw2008/op/assets/52870887/dfe678d2-1d8c-4007-b0d8-3eefbcdb5cd3)
![image](https://github.com/bauw2008/op/assets/52870887/eb2f8a45-407a-44b4-8100-38c4c8e03646)

找到了文件修改了，编译报错
![image](https://github.com/bauw2008/op/assets/52870887/52c8788a-0d6c-4064-aab1-c34fa5ec05aa)
![image](https://github.com/bauw2008/op/assets/52870887/40e591e5-2afd-4cff-af61-dbf33646a2c6)

**Comment by rq1025330** [comment]
> 图片是官方二进制内核文件，和平台不兼容是启动不了的。建议你刷Armbian，用cups做打印服务器更稳定。

cpus 也可以 ？  我主要做3d 打印用

**Comment by rq1025330** [comment]
> 图片是官方二进制内核文件，和平台不兼容是启动不了的。建议你刷Armbian，用cups做打印服务器更稳定。

现在编译成功了 我直接安装的 ipk 替换文件都启动该不了

**Comment by rq1025330** [comment]
> 图片是官方二进制内核文件，和平台不兼容是启动不了的。建议你刷Armbian，用cups做打印服务器更稳定。



> 图片是官方二进制内核文件，和平台不兼容是启动不了的。建议你刷Armbian，用cups做打印服务器更稳定。
已经手动成功了

**Comment by rq1025330** [comment]
> 图片是官方二进制内核文件，和平台不兼容是启动不了的。建议你刷Armbian，用cups做打印服务器更稳定。

![image](https://github.com/bauw2008/op/assets/52870887/39f6afbb-4674-4d14-b4d5-afbb644247c2)
bian'yi'hou编译后文件不是源文件怎呢回事导致无法运行 ，手动替换官网文件0755权限后正常 这是怎么回事

**Comment by rq1025330** [comment]
> > 图片是官方二进制内核文件，和平台不兼容是启动不了的。建议你刷Armbian，用cups做打印服务器更稳定。
> 
> ![image](https://private-user-images.githubusercontent.com/52870887/320271962-39f6afbb-4674-4d14-b4d5-afbb644247c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODM2NDUsIm5iZiI6MTcxMjQ4MzM0NSwicGF0aCI6Ii81Mjg3MDg4Ny8zMjAyNzE5NjItMzlmNmFmYmItNDY3NC00ZDE0LWI0ZDUtYWZiYjY0NDI0N2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA5NDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNjk3NTk4YTgyNGU0M2QzNDAzMjZjMThiMzk4ZTI2ZThlN2Q1ZGIxYjJhMzM5N2Q1NDU2MzE0ZDUzNDU1YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Trq9uELl_1CTB1nEL5szlETpUwmj_MeW8inUb8KJas) bian'yi'hou编译后文件不是源文件怎呢回事导致无法运行 ，手动替换官网文件0755权限后正常 这是怎么回事



> > 图片是官方二进制内核文件，和平台不兼容是启动不了的。建议你刷Armbian，用cups做打印服务器更稳定。
> 
> ![image](https://private-user-images.githubusercontent.com/52870887/320271962-39f6afbb-4674-4d14-b4d5-afbb644247c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODM2NDUsIm5iZiI6MTcxMjQ4MzM0NSwicGF0aCI6Ii81Mjg3MDg4Ny8zMjAyNzE5NjItMzlmNmFmYmItNDY3NC00ZDE0LWI0ZDUtYWZiYjY0NDI0N2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA5NDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNjk3NTk4YTgyNGU0M2QzNDAzMjZjMThiMzk4ZTI2ZThlN2Q1ZGIxYjJhMzM5N2Q1NDU2MzE0ZDUzNDU1YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Trq9uELl_1CTB1nEL5szlETpUwmj_MeW8inUb8KJas) bian'yi'hou编译后文件不是源文件怎呢回事导致无法运行 ，手动替换官网文件0755权限后正常 这是怎么回事

感觉编译的缓存文件样 这个怎么清理

**Comment by rq1025330** [comment]
> 图片是官方二进制内核文件，和平台不兼容是启动不了的。建议你刷Armbian，用cups做打印服务器更稳定。

![image](https://github.com/bauw2008/op/assets/52870887/e837ba17-13cf-40d8-8c94-da208a16531e)
软件好了 ，就是为啥编译后这个文件要改变，手动替换正常
没搞懂原因

**Comment by rq1025330** [comment]
![image](https://github.com/bauw2008/op/assets/52870887/77940b21-bb6d-462a-8bef-1d3acb5058ba)
编译后安装就变

**Comment by bauw2008** [comment]
官方下载的二进制文件，放到源码bin文件下，然后修改下makefile添加这个二进制的位置，再编译即可。或者直接修改其中一个换成你的这个二进制文件。没时间测试，自己测试下吧。这个插件不太怎么使用，只是存档用。

**Comment by rq1025330** [comment]
> 官方下载的二进制文件，放到源码bin文件下，然后修改下makefile添加这个二进制的位置，再编译即可。或者直接修改其中一个换成你的这个二进制文件。没时间测试，自己测试下吧。这个插件不太怎么使用，只是存档用。

我这么干了的 就是安装后文件改变了导致无法运行

**Comment by bauw2008** [comment]
重新拉源码吧，修改了部份

**Comment by rq1025330** [comment]
> 重新拉源码吧，修改了部份

![image](https://github.com/bauw2008/op/assets/52870887/66f46b51-5b14-4f1e-ad8e-ab90f58d2e81)
w我就只这样改的，还加了权限0755 为啥你这文件这么大我才405k
还是不能运行

**Comment by rq1025330** [comment]
![image](https://github.com/bauw2008/op/assets/52870887/b248678d-fb38-4fbf-a59f-f72a990697fc)
安装后文件也变化了

**Comment by rq1025330** [comment]
![image](https://github.com/bauw2008/op/assets/52870887/aab4a8e2-51fd-4292-8da8-31e927cb9fd0)
文件报错提示这个。替换消失
